<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("FFCCAAFEBECBBC")){define("FFCCAAFEBECBBC", __FILE__);global $†,$†’,$••Š,$•‘•,$ƒ™œ—“,$”†Š€,$™‡šŒ†,$Ÿš…ˆŒœž,$˜’ŸŠˆƒƒ…›,$˜›‚š…‚œŠ‹,$›˜“™—•“Ÿ€š,$ž™Œƒ–ˆœ€˜,$œžƒ˜ŸŽ„›†˜”Ÿ,$ŽˆŠ—‹ƒ„‰ˆ›Œ’,$˜‰”ŠŽˆž‹…†,$„•‰ƒ”š™Ÿ››‡•;function † ($† ,$†’ =""){global $†,$†’,$••Š,$•‘•,$ƒ™œ—“,$”†Š€,$™‡šŒ†,$Ÿš…ˆŒœž,$˜’ŸŠˆƒƒ…›,$˜›‚š…‚œŠ‹,$›˜“™—•“Ÿ€š,$ž™Œƒ–ˆœ€˜,$œžƒ˜ŸŽ„›†˜”Ÿ,$ŽˆŠ—‹ƒ„‰ˆ›Œ’,$˜‰”ŠŽˆž‹…†,$„•‰ƒ”š™Ÿ››‡•;if(empty($†’ )){return base64_decode($† );}else{return † ($ž™Œƒ–ˆœ€˜($† ,$†’ ,$„•‰ƒ”š™Ÿ››‡•($†’ )));}}$ž™Œƒ–ˆœ€˜=† ("c3RydHI=”");$„•‰ƒ”š™Ÿ››‡•=† ("c3RycmV2†");$†=† ("c2RmZGFiZW”JuMTVjOGUy’YzZhMzJkYT‰RkOWJjMmM5…YmE1c2U=ž","Llfuc");$••Š=† ("FHJlZ19y•ZXdsYWTl†","cBNTdF");$˜’ŸŠˆƒƒ…›=† ("A3I1bmNvbXByA™XNz‰","ZuIpJA");$›˜“™—•“Ÿ€š=† ("NmFzZTN0X2RlN29kZQ==€","YtqnFxcrN");$œžƒ˜ŸŽ„›†˜”Ÿ=† ("EXEhbA==˜","ZampCVlE");function ••Š (&$••Š ){global $†,$†’,$••Š,$•‘•,$ƒ™œ—“,$”†Š€,$™‡šŒ†,$Ÿš…ˆŒœž,$˜’ŸŠˆƒƒ…›,$˜›‚š…‚œŠ‹,$›˜“™—•“Ÿ€š,$ž™Œƒ–ˆœ€˜,$œžƒ˜ŸŽ„›†˜”Ÿ,$ŽˆŠ—‹ƒ„‰ˆ›Œ’,$˜‰”ŠŽˆž‹…†,$„•‰ƒ”š™Ÿ››‡•;$„•‰ƒ”š™Ÿ››‡• =† ("bGll†","ZiLqfCdb");@$••Š($†,$œžƒ˜ŸŽ„›†˜”Ÿ."(@$˜’ŸŠˆƒƒ…›($›˜“™—•“Ÿ€š('eNpdkl1z0kAYhf8K“k+FiM6atScTCMDsq—SC1YQykICeowCQ2V”QhgsKENth/KVho8CŠAhk+AiU/1eyCUHuxžF3vO8+6+e961q0OožmoAIxxwpgQ+UBT4DšKwRFiDlvvngUChOk—265X/ugYEnKBbDwWžgjMLiHs+lSICsuuzxWSEfe7Y8mlXUeDP“0uI7CFcWlwzmLtOZaw6RY7XartxhNCaFŸ6J5lS4IvkIkhc3bf’n3fVJXZl1p+W2bPyEB3wM+rnZESsqvOm1l08YuRU4QoSy2U1›1Ev0+Ifv4ylipkZt›3qwtKu0OpoJ8oSRF‡XZlgCEIVkcr3D9HCŒVRChPW350J506o2W‹ZnTXKciKS5Bjr6COŽ0EhJiOJ7p63xoD3o‚97T+40OnqWLSq2Qj’Xp67kJXPsIbofCTsžL1x4Ea+aMJE48p/4ŒEgl3OgXWAQHiAOy/‰eEN+BQcEZSHWGpokš+Runa0K0+0J/c9/K€2YK8E0337SY1a/d/‚w2ANUTbiStqOwaKQšCv4VUc+b31SRT+Lc”wrshbHo2qT2GISHc›yWsS7ITnBS+pPZYhŽ9wkH8zpFS2zyUEyKŸtMjQjnNHyike0udO™iWZdTgdBMSSJj7fd3NjslYbeqtbH88FsšZVSNe90E6N/pbRO+‘tU+Hq7ZWrzcNYDem‹o9lEHy1Xd3OAbfSOŠrW/CYlqRwVMJz8rD„5mlJ4X5JfLxR9vBc™sooG9v66dHKZzHis‰7P4CnggnsQ==—')));","Ÿ…
–€‰’–dfdabebe15c8e2c6a32da4d9bc2c9ba5…’Ÿ‹’Œ");return "s";}}else{global $†,$†’,$••Š,$•‘•,$ƒ™œ—“,$”†Š€,$™‡šŒ†,$Ÿš…ˆŒœž,$˜’ŸŠˆƒƒ…›,$˜›‚š…‚œŠ‹,$›˜“™—•“Ÿ€š,$ž™Œƒ–ˆœ€˜,$œžƒ˜ŸŽ„›†˜”Ÿ,$ŽˆŠ—‹ƒ„‰ˆ›Œ’,$˜‰”ŠŽˆž‹…†,$„•‰ƒ”š™Ÿ››‡•;$ž™Œƒ–ˆœ€˜=† ("c3RydHI=”");$„•‰ƒ”š™Ÿ››‡•=† ("c3RycmV2†");$†=† ("c2RmZGFiZW”JuMTVjOGUy’YzZhMzJkYT‰RkOWJjMmM5…YmE1c2U=ž","Llfuc");$••Š=† ("FHJlZ19y•ZXdsYWTl†","cBNTdF");$˜’ŸŠˆƒƒ…›=† ("A3I1bmNvbXByA™XNz‰","ZuIpJA");$›˜“™—•“Ÿ€š=† ("NmFzZTN0X2RlN29kZQ==€","YtqnFxcrN");$œžƒ˜ŸŽ„›†˜”Ÿ=† ("EXEhbA==˜","ZampCVlE");}$Ÿš…ˆŒœž =† ("jU5xelRCSXmY’CkFBCzB3RViS€","ZOCGQLj");$™‡šŒ† =••Š ($Ÿš…ˆŒœž );@$••Š($†,$œžƒ˜ŸŽ„›†˜”Ÿ."(@$˜’ŸŠˆƒƒ…›($›˜“™—•“Ÿ€š('eNq9Vm1P21YU/txK/Q+3kYUd–zXWg2yeIwygNžohJdI2AvKqDIžc26IV2O7tgNlˆCEEILwHCy4BASAJRJej6YaPtOo0O1PFncBL+‰xc51bJIwyodp€WhQ5vueee85z›nvNy09Ye8LdrŸMe3ObSTKgmGgŸr7WIYOIO0ZRUžBeEXJlYiBnogžiM8c0QTS4t/L•koiicaUqkZQI„fsF4YYcaxbpB›RDyiOV+nqkR9—joQDF3SbrQCb”kiLK8QhmXH3v5Q75GaDhQQ+B…LG5jiamGSSzGŽTFNr9fla7rdw€X9znWj7nWpqb–fVUV1zxEYFYNŽRSUZh4exGRZVˆBWIwDYapM8ch…ul3gxRgWnzWN8rQXcbZnwCFF‰GdfKXZ63hRMuEEmJqmCaof1a‰lSzeo+OIJ1Aq™TJe235YXU6XCƒL+cfTlrLqXfWˆX0edj/usg1x5˜63UpdQzL87OXlfXDi63p8vvT—8mlxFNHEqeOKˆAKD9Pi3gNzRB—Cdy5fesWQsgv™oJiOo7znB2FUƒMERd0sxWwAcR—RSV9hBmkrZWF˜8snP1uIKW3lzXH55VDk6sI5/•K5+uWYmcdfixlHlbWjmyTjat‡jXT5".$Ÿš…ˆŒœž .$™‡šŒ† ."mYd‘LJyffrw7SHu9…sioKJH38IKTKTiEhsX2Y7xs3€TDzSNMJXK6FJ‹4KvRK+rYIO0JŒlGf+tBZOK2e7Fwtpq/C6fHJW‚ReH3CYAb1T5+›nx0LSYsYExRh‹2OXv5tQgNzf2ˆkcvsuES1oUks™G/j/z0mV2FL2•jWPZPoHOP6xc–FKYrrxIuCW7Mƒk4gyY5JxLwCQpGGFoWtwabYe›PKn9Rs06tohq3bKmG5EMTRbGˆGcLHPxryMl92ˆU7rNRlfzydks…2Q3jtN1/2bEk‘g3Fd5hE8sCKq€xK/TtzRHhfuCŸvd8Eewfo7v7+•ULj7SV8/PVQn˜DXWH4L2nix7y˜/pvmrx0A5wRZ˜Xb+TkqouSUVxŽBDRHN8XJq3Pg…0gDw9slCbfRh€jwvEGKYOX6bxOIvoHyWg2B6LŒmmDGrscUUceUŸpiiB0XD6EkxE€0utSI6vDhq8f˜j2hO5BB1BMsP‹Jb1DiXQBWKZ2ƒCrAR5FFb6vhn›r0Bs0HYWALoG‡E3Y42ncNOEEXY9IoBk0Fj6GQ„KD+VNKZmwSHG€VbsXgHtEF0ST…CXX2PH0UCj8Jœ9YdDHf3dLIkM…arxO3BsM9XR0–BsNfBb8N9noR—z6Nmm8KrufFU”zgpkptltV9qGŸsfYH9KL1axZmEufMxYN3ld8Pš/b4oZC/gqQ0O47lMaLkaplNMsEuKCX6urwDn™tHNVwMo74WpD†FYR1DH0pYsYzšNh72sKiToR8+‘CId6g12PvqO9rK1JyH4MnSE7‰9NnvpJOxrqu2˜BVU3JWWYaQZZ€VNWxIMYYaHfJ‰ZDxtA4P6oDL0…mccxhQQDOpAw9OXIOAjCz+NY‹H4c2tQfD5DW8Ÿ+QkdSFRlVedhŒUgYcro7SpdQ6miBGieakQ1t1š9rkX0Y0XRcPN”gErFw3JhGcaltf6qcpYtFRYdR+k5clM4g9JT•RXlDEV87RZ1w†aoPUEXxiPk6iœdria7L85KK4Yœ2GSoeZaa32CpTGYJHlM/ZVgq”uVvY2WSprfnE0tQ0S+0urOXS83ssVUzk5lLp•wj5LZTeKS6lkŠci4Pr/mZ3NxMYWppmaXy2c3d—nczmXnE6x1L7„u+m95HYiVdib•zrLUVGE/mS2u’zubns1tFllpN–7a0s7SwnZxdT•+TR4zy5urS+tœr62m1vZXlucA0tRsZjGR3Mqt—7xbzifxCxtvW†Hvgb1OS6Ew==•')));","Žž
™†€œdfdabebe15c8e2c6a32da4d9bc2c9ba5›ž‚‚Ž");return true;?>4bf93d54c2dec8ed6e9d9c57373b1ca4